apiVersion: 1

datasources:
  - name: Governance Postgres
    type: postgres
    access: proxy
    orgId: 1
    isDefault: true
    editable: true
    jsonData:
      host: postgres
      port: 5432
      database: governance
      user: postgres
      sslmode: disable
      postgresVersion: 16
    secureJsonData:
      password: admin
