apiVersion: 1
datasources:
  - name: Governance Postgres
    uid: governance-postgres
    type: postgres
    access: proxy
    orgId: 1
    url: postgres:5432
    database: governance
    user: postgres
    secureJsonData:
      password: admin
    isDefault: true
    jsonData:
      sslmode: disable
