apiVersion: 1

datasources:
  - name: Governance Postgres
    type: postgres
    access: proxy
    orgId: 1
    isDefault: true
    editable: true

    url: postgres:5432
    user: postgres
    database: governance

    jsonData:
      sslmode: disable
      postgresVersion: 1500

    secureJsonData:
      password: admin